DISTRO = "techleef"
DISTRO_NAME = "TechLeef Distribution"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "best"

INIT_MANAGER = "systemd"

TCLIBCAPPEND = ""

DISTRO_FEATURES = "\
    ipv4 \
    ipv6 \
    ldconfig \
    usbgadget \
    usbhost \
    usrmerge \
    vfat \
    wifi \
"

NO_RECOMMENDATIONS = "1"
DISTRO_EXTRA_RDEPENDS = ""
DISTRO_EXTRA_RRECOMMENDS = ""

include recipes-kernel/linux/cve-exclusion.inc
include recipes-kernel/linux/cve-exclusion_6.6.inc
include conf/distro/include/cve-extra-exclusions.inc
#INHERIT += "cve-check"


INHERIT += "create-spdx"
SPDX_PRETTY = "1"
