
require conf/machine/raspberrypi0-2w-64.conf

MACHINE_FEATURES = ""
MACHINE_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

RPI_USE_U_BOOT = "1"
ENABLE_I2C = "1"
ENABLE_UART = "1"

KERNEL_DEVICETREE = "\
    broadcom/bcm2710-rpi-zero-2.dtb \
    overlays/overlay_map.dtb \
"
